Support ES modules (#77)
* Add rollup devDependency

This will be used to bundle the ES module into a UMD module

* Rename idb.js -> idb.mjs

This is in preparation for converting it to an ES module

It is done as a separate commit to preserve the git history associated
with the file.

* Convert idb source code to an ES module

* Add compiled UMD bundle to source control

* Export open and delete separately

We have to name the delete function _delete in the declaration to work
around this error:
```
Error: Unexpected keyword 'delete'
```

* Move built lib/idb.js UMD bundle into a build directory

* Rename open to openDb and delete to deleteDb

This avoids the hassle caused by having an export that matches a keyword
(delete). It's a breaking change but it should be easy for users to
migrate to this API.

* Bump to version 3.0.0

* Getting rid of the tests. They were incomplete and pretty useless.

* Minor docs and types changes